### ISSUE TITLE
Ready for review

### ISSUE THREAD

**Issue by bakura10** [zf-fr/zfr-eb-worker#1]
ping @danizord

Few questions:
- Should we provide a simple JobInterface wrapper instead of using plain array?
- Should we rename this to zfr-eb-worker (as it's really a wrapper to be used with Elastic Beanstalk)
- Anything else?

**Comment by danizord** [comment]
@bakura10 everything looks good for me :clap: :clap: 

> Should we provide a simple JobInterface wrapper instead of using plain array?

Not needed IMHO. We can handle creation of meaningful command objects in the matched middlewares.

> Should we rename this to zfr-eb-worker (as it's really a wrapper to be used with Elastic Beanstalk)

Yeah I prefer `zfr-eb-worker`.

> Anything else?

Great work :+1:

**Comment by bakura10** [comment]
Done!

I've completely unit-tested it :).
