### ISSUE TITLE
Update for PSR-15

### ISSUE THREAD

**Issue by bakura10** [zf-fr/zfr-eb-worker#33]
ping @danizord

**Comment by danizord** [comment]
As discussed on Slack, we'll wait until PSR-15 gets approved.

**Comment by danizord** [comment]
@bakura10 I think we can implement latest interop interfaces since Stratigility is going to support it :) https://github.com/zendframework/zend-stratigility/pull/96

**Comment by bakura10** [comment]
Awesome ^^. Let's wait a big for 6.0.0 release then. Question as you've studied it: when we'll upgrade to 6 in our projects we'll need to update all them all.

I suppose this won't work if our code uses Stratigility 1 and ZfrEbWorker that would used Stratigility 2 right? This would mean that we would need first to update all the projects to Stratigility 2 before having a chance to upgrade? Or does Expressive takes care of that and it iwll make transparnet?

**Comment by danizord** [comment]
Yeah, we'll need to update existing projects to Stratigility 2 and Expressive 2 to be able to use ZfrEbWorker 6 :)

**Comment by danizord** [comment]
Fixed by #44
