### ISSUE TITLE
Add additional security to prevent route to be accessible in web environment

### ISSUE THREAD

**Issue by bakura10** [zf-fr/zfr-eb-worker#34]
For now, we have a middleware that verify the incoming request to internal worker route is made from localhost (https://github.com/zf-fr/zfr-eb-worker/blob/master/src/Middleware/LocalhostCheckerMiddleware.php).

In addition to that, we may add an environment variable (like "EB_WORKER_DISABLED") that, if set to true (for instance in an web environment) simply return an error (either exception as now or, even better, a 403 response).

**Comment by danizord** [comment]
Since Expressive 1.1 middlewares are piped manually, so we can simply not pipe `WorkerMiddleware` if not in worker environment:
```php
if (getenv('ENV_TYPE') === 'worker') {
    $app->pipe('internal/worker', WorkerMiddleware::class);
}
```

**Comment by bakura10** [comment]
Pretty nice !

**Comment by danizord** [comment]
I'm closing in favor of the other approach that does not require any changes in the library.
