### ISSUE TITLE
Wrong docker IP detection with docker for Mac

### ISSUE THREAD

**Issue by wysow** [zf-fr/zfr-eb-worker#50]
Here https://github.com/zf-fr/zfr-eb-worker/blob/93078f58a54b623dfa6a28503892f4738ccba957/src/Middleware/WorkerMiddleware.php#L157 the docker IP detection seems to be wrong when using docker for Mac, my container IP is `172.18.0.1` so the right regexp could be something like `172.1*.*` maybe...

**Comment by bakura10** [comment]
That sounds like a nice tradeoff. Can you make a PR?

**Comment by wysow** [comment]
Just done ;) if this PR seems OK for you, sounds good for you to tag a new release?
