### ISSUE TITLE
Considering little optimization on 5.3 release

### ISSUE THREAD

**Issue by wysow** [zf-fr/zfr-eb-worker#55]
Hello,

We do have one of our microservices on php 7.0 and so using 5.3 release of this library, but we are facing a problem with how messages are created, do you think we can add this little fix in `doFlush` function of `MessageQueue` class after line 111:

```php
'MessageAttributes' => [
    'Name' => [
        'DataType'    => 'String',
        'StringValue' => $message['body']['name'],
    ],
],
```

So that the message name can be retrieved by another micro-service using latest release?

**Comment by wysow** [comment]
Seems like php 7.1 listener should handle both message type if we do that, right?

**Comment by bakura10** [comment]
Hi,

We didn't keep a branch for 5.x version and master is on 6.x. @danizord , what would be the best approach to release a version of 5.x branch to include this?

**Comment by danizord** [comment]
@bakura10 just pushed a `release/5.3.0` branch based on `5.3.0` tag.

@wysow can you send a PR targeting this branch? We'll merge it and release 5.3.1 :)

**Comment by wysow** [comment]
Sure wiil do, already done this on our fork ;) do you confirm that our solution sounds good for you?

**Comment by bakura10** [comment]
Yes the solution looks good :). It's actually something I should have done to help migrate between the two different message models.

**Comment by wysow** [comment]
PR done in #56
