### ISSUE TITLE
How to handle AWS internal events

### ISSUE THREAD

**Issue by wysow** [zf-fr/zfr-eb-worker#57]
Hello,

One more problem we are facing is how can we handle AWS internal events as they do not have the `message attribute name`, for example a S3 `putObject` event sent to a SQS queue... 

Simple solution we are thinking of would be to handle the case in the `WorkerMiddleware` class to set a `default` name for the message somehow... Maybe using the simple `default-message` string but we think that there could be some edge cases doing this... What do you think ?

More complex solution could be to handle more accurately all kind of internal AWS events, extracting some information from the payload body...

**Comment by danizord** [comment]
Fixed by #59
